name: RoadRegistryTests

on:
  push:
    branches:
      master

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup openjdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Install using maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

